name: qt5-application
version: 1
summary: Qt5 Application Example
description: A simple text editor
confinement: strict

apps:
  qt5-application:
    command: desktop-launch application
    plugs: [unity7, home]

parts:
  application:
    source: src/
    plugin: qmake
    qt-version: qt5
    after: [desktop-qt5-only]

  # After copying the part source dir "qt" to your local project
  # Copy this part definition into your snapcraft.yaml
  desktop-qt5-only:
    source: ../../qt        # wherever the part's source lives
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
